name: Compile Apps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Compile
      run: make compile

    - name: test
      run: make test

    - name: Comment PR
            uses: thollander/actions-comment-pull-request@v2
            with:
              message: |
                Hello world ! :wave:
